# Generated by Django 2.2.8 on 2023-04-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2004-05-02'),
            preserve_default=False,
        ),
    ]
